# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-16 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('image', models.ImageField(blank=True, upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('path', models.CharField(blank=True, max_length=1000, null=True)),
                ('task_id', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField()),
                ('status', models.CharField(choices=[('Q', 'QUEUED'), ('D', 'DOWNLOADED'), ('S', 'SKIPPED')], default='S', max_length=2)),
                ('album', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='music.Album')),
            ],
        ),
    ]
