# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-16 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
