# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-18 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_remove_track_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='pid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
