# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-16 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0002_auto_20181216_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='auth_type',
            field=models.CharField(choices=[('B', 'BASIC'), ('P', 'POST PARAM'), ('H', 'HEADER'), ('C', 'COOKIE')], default='B', max_length=2),
        ),
        migrations.AddField(
            model_name='client',
            name='token_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
